// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUWGQgBTf1OBXqLlBQ0ZiGnk-GrJa3FU',
    appId: '1:941471556278:web:1644f2f9c839ade308fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    authDomain: 'ell-tall-market.firebaseapp.com',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    measurementId: 'G-EZE5HCT5X5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSk8EfZdGE8JGoqE1cA6dAcGXY_Q9YotQ',
    appId: '1:941471556278:android:bf44b6b731a4381608fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASu5cSMyRqpmAxYKs8Pvn_dpnmUueHD_I',
    appId: '1:941471556278:ios:4c0dd18cfe52d56808fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    androidClientId: '941471556278-g0d409tmu6qv6oskauhkgbu04ko9faci.apps.googleusercontent.com',
    iosClientId: '941471556278-341l68isfcd7q6peegu4i5p41emunml0.apps.googleusercontent.com',
    iosBundleId: 'com.elltall.market',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASu5cSMyRqpmAxYKs8Pvn_dpnmUueHD_I',
    appId: '1:941471556278:ios:4c0dd18cfe52d56808fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    androidClientId: '941471556278-g0d409tmu6qv6oskauhkgbu04ko9faci.apps.googleusercontent.com',
    iosClientId: '941471556278-341l68isfcd7q6peegu4i5p41emunml0.apps.googleusercontent.com',
    iosBundleId: 'com.elltall.market',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKUWGQgBTf1OBXqLlBQ0ZiGnk-GrJa3FU',
    appId: '1:941471556278:web:da2c01bec1d888db08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    authDomain: 'ell-tall-market.firebaseapp.com',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    measurementId: 'G-J3ZB63S986',
  );
}
