// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKUWGQgBTf1OBXqLlBQ0ZiGnk-GrJa3FU',
    appId: '1:941471556278:web:8bb6af8ae5e3ce9f08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    authDomain: 'ell-tall-market.firebaseapp.com',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    measurementId: 'G-0E4TLRX3XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSk8EfZdGE8JGoqE1cA6dAcGXY_Q9YotQ',
    appId: '1:941471556278:android:1d90df64a0f9fc2a08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASu5cSMyRqpmAxYKs8Pvn_dpnmUueHD_I',
    appId: '1:941471556278:ios:1ae1f350fb80520e08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    iosClientId: '941471556278-o98nlsdrf39jl1f1v2k8g4f4f64mbqnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ellTallMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASu5cSMyRqpmAxYKs8Pvn_dpnmUueHD_I',
    appId: '1:941471556278:ios:1ae1f350fb80520e08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    iosClientId: '941471556278-o98nlsdrf39jl1f1v2k8g4f4f64mbqnf.apps.googleusercontent.com',
    iosBundleId: 'com.example.ellTallMarket',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAKUWGQgBTf1OBXqLlBQ0ZiGnk-GrJa3FU',
    appId: '1:941471556278:web:712cd5f045134ffc08fc17',
    messagingSenderId: '941471556278',
    projectId: 'ell-tall-market',
    authDomain: 'ell-tall-market.firebaseapp.com',
    storageBucket: 'ell-tall-market.firebasestorage.app',
    measurementId: 'G-992RHG7DS7',
  );
}
